import './globals.d.ts';
/* tslint:disable */
/* eslint-disable */
/**
 * 鉴权接口文档 - version 1.0.0
 *
 * 用户登录、注册、注销、获取用户信息等接口文档
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.logout': ['POST', '/auth/logout'],
  'general.login': ['POST', '/auth/login']
};
