import './globals.d.ts';
/* tslint:disable */
/* eslint-disable */
/**
 * 系统模块接口文档 - version 1.0.0
 *
 * 用户、角色、权限等接口文档
 *
 * OpenAPI version: 3.0.1
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'general.getInitInfo': ['POST', '/system/workbenchConfig/getBaseInfo']
};
